### PR TITLE
Web: SVG - Fix Compile Error

### PR DESCRIPTION
**Pull request by hfhbd**
@eymar

### CODE REVIEW

**Comment by eymar** [comment]
What was the error ? :)

**Review by eymar — APPROVED** [review]

**Comment by hfhbd** [comment]
```
Using Kotlin/JS IR backend

Using Kotlin/JS incremental compilation

file or directory '/mnt/agent/work/cf85b5b43f56097b/web/svg/build/externals/web-web-svg/src', not found

file or directory '/mnt/agent/work/cf85b5b43f56097b/web/svg/src/commonMain/kotlin', not found

file or directory '/mnt/agent/work/cf85b5b43f56097b/web/svg/src/commonMain/kotlin', not found

e: /mnt/agent/work/cf85b5b43f56097b/web/svg/src/jsMain/kotlin/org/jetbrains/compose/web/svg/svg.kt: (498, 13): None of the following functions can be called with the arguments supplied: 

public fun AttrsScope<SVGElement>.points(vararg points: Number): Unit defined in org.jetbrains.compose.web.svg in file svgAttrs.kt

public fun AttrsScope<SVGElement>.points(points: String): Unit defined in org.jetbrains.compose.web.svg in file svgAttrs.kt

e: /mnt/agent/work/cf85b5b43f56097b/web/svg/src/jsMain/kotlin/org/jetbrains/compose/web/svg/svg.kt: (515, 13): None of the following functions can be called with the arguments supplied: 

public fun AttrsScope<SVGElement>.points(vararg points: Number): Unit defined in org.jetbrains.compose.web.svg in file svgAttrs.kt

public fun AttrsScope<SVGElement>.points(points: String): Unit defined in org.jetbrains.compose.web.svg in file svgAttrs.kt

Restoring task outputs to pre-compilation state
```

**Comment by hfhbd** [comment]
`Points` is a `Array<Number>` which does not work with the vararg overload without explicit adding parameter name.

**Comment by eymar** [comment]
> `Points` is a `Array<Number>` which does not work with the `vararg Number` overload without explicitly adding parameter name.

Thanks

**Pull request merged**
