### PR TITLE
Compress main README.md png

### PR DESCRIPTION
**Pull request by YektaDev**
Compress artwork/readme/apps.png

### CODE REVIEW

**Comment by igordmn** [comment]
Compressed image has visible artifacts:
image

What tool did you use?

**Comment by YektaDev** [comment]
Oh I didn't notice that. I used TinyJPG's extension.

**Comment by YektaDev** [comment]
Should I close this PR?

**Comment by igordmn** [comment]
Feel free to close :). Thanks!

If you will have compressed png without artifacts, you can reopen this PR.

**Pull request closed without merging**
