### PR TITLE
Fixed compilation of web getting-started tutorial

### PR DESCRIPTION
**Pull request by solidogen**
I followed the tutorial here:
https://github.com/JetBrains/compose-jb/blob/master/tutorials/Web/Getting_Started/README.md

Yet code inside doesn't compile. I checked actual code from an example and it differs:
https://github.com/JetBrains/compose-jb/blob/master/examples/web-getting-started/src/jsMain/kotlin/Main.kt

I updated tutorial with code from example so it compiles and runs correctly.

### CODE REVIEW

**Comment by eymar** [comment]
Hi @solidogen 
Could you please let us know what was the error when you tried to compile the code from the tutorial?

I will update the code in example to match the code in the tutorial. The code in the tutorial is more idiomatic, so the web-getting-started example should match it.

**Comment by eymar** [comment]
I updated the code in the example and added a note in the tutorial:
https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Getting_Started#7-add-the-mainkt-file

One might need to add imports:
```
import androidx.compose.runtime.getValue
import androidx.compose.runtime.setValue
```

But let us know if you had another compilation error.

**Review by olonho — COMMENTED** [review]
Yes, this looks like missing imports.

**Comment by solidogen** [comment]
Yeah, I added getValue import because I remember there were problems, but I totally forgot setValue as well. Closing, thanks

**Pull request closed without merging**
