### PR TITLE
Apple Silicon build fixes for todoapp

### PR DESCRIPTION
**Pull request by treitter**
These commits make the `todoapp` example buildable on Apple Silicon (eg, M1 chips).

There's a common bit of logic copied throughout four `build.gradle.kts` files for the `iosTarget` value. It should be factored out but I was unable to do so. It depends on Kotlin Gradle DSL symbols which I can't seem to import or otherwise access outside of the (various) `kotlin` blocks in the Gradle files. Help refactoring that would be appreciated!

### CODE REVIEW

**Review by dima-avdeev-jb — COMMENTED** [review]
Thanks for PR!
You successfully fix build on Mac M1!
But, unfortunately build on Mac with Intel CPU fails.

I will try to fix this build on Intel CPU's in different branch.
So I change destination of PR to temp branch.

**Comment by dima-avdeev-jb** [comment]
@treitter 
I made changes in your fork.
Can you please review and merge PR: https://github.com/treitter/compose-jb/pull/1
After that I also can approve your PR

**Comment by treitter** [comment]
Ready for a final review and merge

**Review by dima-avdeev-jb — APPROVED** [review]
All fine, now you can merge your PR

**Comment by treitter** [comment]
@dima-avdeev-jb sorry, I just realized this doesn't quite work. I thought I did a clean build in my testing but I must have had some stale artifacts around because after I did thorough build cleaning, I get build failures:

```
CompileSwift normal arm64 /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/MainView.swift (in target 'TodoApp' from project 'TodoApp')
    cd /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/ContentView.swift -primary-file /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/MainView.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/EditView.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/TodoApp.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/ListView.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/ComponentHolder.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/RootView.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/SimpleRouterState.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/InputView.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/MutableStateBuilder.swift /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/ObservableValue.swift -emit-dependencies-path /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/ContentView.d -emit-reference-dependencies-path /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/ContentView.swiftdeps -serialize-diagnostics-path /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/ContentView.dia -emit-dependencies-path /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/MainView.d -emit-reference-dependencies-path /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/MainView.swiftdeps -serialize-diagnostics-path /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/MainView.dia -target arm64-apple-ios14.0-simulator -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.4.sdk -I /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Products/Debug-iphonesimulator -F /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Products/Debug-iphonesimulator -F /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/common/root/build/xcode-frameworks/Debug/iphonesimulator15.4 -enable-testing -g -module-cache-path /Users/treitter/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -new-driver-path /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-driver -serialize-debugging-options -Xcc -working-directory -Xcc /Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/TodoApp-generated-files.hmap -Xcc -I/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/TodoApp-own-target-headers.hmap -Xcc -I/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/TodoApp-all-target-headers.hmap -Xcc -iquote -Xcc /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/TodoApp-project-headers.hmap -Xcc -I/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/DerivedSources-normal/arm64 -Xcc -I/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/DerivedSources/arm64 -Xcc -I/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/DerivedSources -Xcc -DDEBUG\=1 -module-name TodoApp -target-sdk-version 15.4 -o /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/ContentView.o -o /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/MainView.o -index-unit-output-path /TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/ContentView.o -index-unit-output-path /TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/MainView.o -index-store-path /Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Index/DataStore -index-system-modules

/Users/treitter/AndroidStudioProjects/compose-jb/examples/todoapp/ios/ios/ContentView.swift:2:8: error: no such module 'Todo'
import Todo
       ^
/Users/treitter/Library/Developer/Xcode/DerivedData/TodoApp-gromamvunytcevfkmpzvainyrola/Build/Intermediates.noindex/TodoApp.build/Debug-iphonesimulator/TodoApp.build/Objects-normal/arm64/MainView.dia:1:1: warning: Could not read serialized diagnostics file: error("Invalid diagnostics signature") (in target 'TodoApp' from project 'TodoApp')
Command CompileSwift failed with a nonzero exit code
```

It seems obvious that we need to change the Xcode project framework arguments to `-framework KotlinCommon` and update the import lines in each of the Swift files to `import KotlinCommon` but I get similar build failures just with "no such modules: 'KotlinCommon'".

I tried this many different ways but can't seem to solve the problem.

Meanwhile, my original branch with the kludgey `iosTarget()` functions still works reliably.

Maybe if you can confirm the latest version of `master` clean-builds reliably for you on Intel, I can narrow down the minimum difference between my working branch and `master`.

**Comment by dima-avdeev-jb** [comment]
@treitter 
Yeah, i see.
Unfortunately I also miss this error, because of build caches.

Thanks for investigation!
I will try to fix it in another PR!

**Comment by dima-avdeev-jb** [comment]
We can continue discussion at this PR:
https://github.com/JetBrains/compose-jb/pull/2024

**Pull request merged**
